---
- name: Installation of web server
  hosts: all
  tasks:
  - name: install httpd
    yum:
     name: httpd
     state: present
    
  - name: create a webpage
    copy:
     content: " hello ivan, this playbook2-for webserver"
     dest: /var/www/html/index.html
   
  - name: start a web service
    service:
      name: httpd
      state: started
      enabled: true

